
/*

		NAME 	 - Local Planner Node 
		DESIGN - Yan Sleight
		PRIORITY - Feature - Not required for basic functionality, required for navigation
	
		--------OVERVIEW--------
This node takes in the Current position and the next position (as generated by the global planner)
and generates velocity message to reach this position.

		--------FUTURE WORK--------
This node has been tested with dummy data, but never real world data. Testing is required to insure
that it is correctly working with the global planner and generating correct velocity messages.

*/

#include "ros/ros.h"
#include "LocalPlanner.h"


using namespace std;


int main(int argc, char **argv)
{
	ros::init(argc, argv, "LocalPlannerNode");
	
	LocalPlanner planner;
	geometry_msgs::Twist data;
	
	planner.init(argc, argv);

	ros::Rate r(10); // 10 hz, decide appropriate value plz
	while (ros::ok())
	{
		ros::spinOnce();
		
		planner.move_to_point();
		
		data.linear.x = 0;
		data.linear.y = 0;
		data.linear.z = 0;
		data.angular.x = 0;
		data.angular.y = 0;
		data.angular.z = 0;
		
		switch (planner.direction_out)
		{
		case 0:
		    data.linear.x = planner.velocity_out;
		case 2:
		    data.linear.x = -planner.velocity_out;
		case 3:
		    data.linear.y = planner.velocity_out;
		case 1:
		    data.linear.y = -planner.velocity_out;
		case 5:
		    data.angular.z = planner.velocity_out;
	    case 4:
		    data.angular.z = -planner.velocity_out;
		}
		
		planner.pub.publish(data);
		r.sleep();
	}


}


